CREATE_TABLE_CAMERA = """
CREATE TABLE IF NOT EXISTS camera (
    name VARCHAR(255) PRIMARY KEY NOT NULL,
    make VARCHAR(255) NOT NULL,
	model VARCHAR(255) NOT NULL,
    lat FLOAT NOT NULL,
    lon FLOAT NOT NULL
)
"""

CREATE_TABLE_PHOTO = """
CREATE TABLE IF NOT EXISTS photo (
    id CHARACTER(32) PRIMARY KEY NOT NULL,
    path VARCHAR(255) NOT NULL UNIQUE,
    lat FLOAT NOT NULL,
    lon FLOAT NOT NULL,
    time DATETIME NOT NULL,
    camera_id VARCHAR(255) NOT NULL,
    FOREIGN KEY(camera_id) REFERENCES camera(name)
)
"""

CREATE_TABLE_MODEL = """
CREATE TABLE IF NOT EXISTS model (
    id CHARACTER(16) PRIMARY KEY NOT NULL,
    name VARCHAR(255) NOT NULL,
    x0 INTEGER NOT NULL,
    y0 INTEGER NOT NULL,
    x1 INTEGER NOT NULL,
    y1 INTEGER NOT NULL,
    model VARCHAR(255) NOT NULL,
    photo_id CHARACTER(16) NOT NULL,
    FOREIGN KEY(photo_id) REFERENCES photo(id)
)
"""
